//LOGIN
export const LOGIN = 'LOGIN';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
//REQUEST
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
//GET EXPRESSIONS
export const FETCH_EXPRESSIONS = 'FETCH_EXPRESSIONS';
export const FETCH_EXPRESSIONS_SUCCESS = 'FETCH_EXPRESSIONS_SUCCESS';
export const FETCH_EXPRESSIONS_FAILURE = 'FETCH_EXPRESSIONS_FAILURE';
//REMOVE_EXPRESSION
export const REMOVE_EXPRESSION = 'REMOVE_EXPRESSION';
export const REMOVE_EXPRESSION_SUCCESS = 'REMOVE_EXPRESSION_SUCCESS';
export const REMOVE_EXPRESSION_FAILURE = 'REMOVE_EXPRESSION_FAILURE';
//UPDATE_EXPRESSION_ID
export const UPDATE_EXPRESSION = 'UPDATE_EXPRESSION';
export const UPDATE_EXPRESSION_SUCCESS = 'UPDATE_EXPRESSION_ID';
export const UPDATE_EXPRESSION_FAILURE = 'UPDATE_EXPRESSION_ID';

export const SET_DISPLAY = 'SET_DISPLAY';
export const SET_EXPRESSION = 'SET_EXPRESSION';
export const SET_EXTENDED = 'SET_EXTENDED';
export const HANDLE_FORM = 'HANDLE_FORM';
