//LOGIN
export const LOGIN = 'LOGIN';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
//REQUEST
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
//GET EXPRESSIONS
export const FETCH_EXPRESSIONS = 'FETCH_EXPRESSIONS';
export const FETCH_EXPRESSIONS_SUCCESS = 'FETCH_EXPRESSIONS_SUCCESS';
export const FETCH_EXPRESSIONS_FAILURE = 'FETCH_EXPRESSIONS_FAILURE';
//REMOVE_EXPRESSION
export const REMOVE_EXPRESSION = 'REMOVE_EXPRESSION';
export const REMOVE_EXPRESSION_SUCCESS = 'REMOVE_EXPRESSION_SUCCESS';
export const REMOVE_EXPRESSION_FAILURE = 'REMOVE_EXPRESSION_FAILURE';
//UPDATE_EXPRESSION_ID
export const UPDATE_EXPRESSION = 'UPDATE_EXPRESSION';
export const UPDATE_EXPRESSION_SUCCESS = 'UPDATE_EXPRESSION_ID';
export const UPDATE_EXPRESSION_FAILURE = 'UPDATE_EXPRESSION_ID';
//EQUATIONS
export const GET_EQUATION = 'GET_EQUATION';
export const GET_EQUATION_SUCCESS = 'GET_EQUATION_SUCCESS';
export const GET_EQUATION_FAILURE = 'GET_EQUATION_FAILURE';
export const SOLVE_EQUATION = 'SOLVE_EQUATION';
export const SOLVE_EQUATION_SUCCESS = 'SOLVE_EQUATION_SUCCESS';
export const SOLVE_EQUATION_FAILURE = 'SOLVE_EQUATION_FAILURE';
//STATISTIC
export const GET_USER_ROLE_STATISTIC = 'GET_USER_ROLE_STATISTIC';
export const GET_USER_ROLE_STATISTIC_SUCCESS =
  'GET_USER_ROLE_STATISTIC_SUCCESS';
export const GET_USER_ROLE_STATISTIC_FAILURE =
  'GET_USER_ROLE_STATISTIC_FAILURE';
export const GET_EXPRESSION_STATISTIC = 'GET_EXPRESSION_STATISTIC';
export const GET_EXPRESSION_STATISTIC_SUCCESS =
  'GET_EXPRESSION_STATISTIC_SUCCESS';
export const GET_EXPRESSION_STATISTIC_FAILURE =
  'GET_EXPRESSION_STATISTIC_FAILURE';
export const GET_EXPRESSION_USER_STATISTIC = 'GET_EXPRESSION_USER_STATISTIC';
export const GET_EXPRESSION_USER_STATISTIC_SUCCESS =
  'GET_EXPRESSION_USER_STATISTIC_SUCCESS';
export const GET_EXPRESSION_USER_STATISTIC_FAILURE =
  'GET_EXPRESSION_USER_STATISTIC_FAILURE';

export const SET_DISPLAY = 'SET_DISPLAY';
export const SET_EXPRESSION = 'SET_EXPRESSION';
export const SET_EXTENDED = 'SET_EXTENDED';
export const HANDLE_FORM = 'HANDLE_FORM';
